\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{whuthkrep}[2020/10/21 武汉大学思想汇报模板]

\LoadClass[zihao=-4]{ctexart}

\AtBeginDocument{%
\begin{center}
    \Large 思想汇报
\end{center}

\noindent 敬爱的党组织：

在组织的关怀和党员的熏陶下，我的思想不断得到磨炼和提高，先向组织汇报一下近段时间的情况。

}

\AtEndDocument{\par%
以上是我在思想、工作、学习方面的汇报，我要不断总结工作
和生活中的经验和教训，严格要求自己，自觉接受组织和同学们的监督，严于律己，奋勇前进，努力向一名党员看齐。

此致\\敬礼

\begin{flushright}
    汇报人：\@author

    \@date
\end{flushright}
}
